### PR TITLE
feat(de): impl deserialize_ignored_any

### PR DESCRIPTION
**Pull request by cathaysia**

### CODE REVIEW

**Comment by cathaysia** [comment]
This method is implemented because in some cases it may be necessary to skip fields. At this time, cdr is required to implement the IgnoreAny method

**Comment by hrektts** [comment]
I don't understand why this is needed. Could you please clarify the issue, show deficiencies against the specifications, and provide some examples?

**Comment by cathaysia** [comment]
Just guess we receive a data like this:

```console
+----+-------+
| k1 |  cdr1 |
+----+-------+
| k2 | cdr2  |
+----+-------+
| k3 | cdr3  |
+----+-------+
| .. | ....  |
+----+-------+
```
I need to deserialize this data into a structure, a common way is to use [serde_map](https://docs.rs/serde/1.0.171/serde/de/trait.Visitor.html#method.visit_map) :
```rust
fn visit_map(){
    while xxx.get_next_key()? {
        k1 => { yyy = map.next_value()? }
        k2 => { yyy = map.next_value()? }
        _  => { // unknown key, we need skip it.
           let _: IngoreAny = map.next_value()?
       }
   }
}
```

As shown above, if we encounter an unrecognized key, we need to skip it, using IgnoreAny. This requires implementing the IngnreAny method

**Comment by hrektts** [comment]
`CDR` is not a `self-describing` format. You cannot implement `deserialize_any` and `deserialize_ignored_any` as [the documentation says](https://serde.rs/impl-deserializer.html#implementing-a-deserializer). The workaround you suggest is outside the scope of the crate.

**Pull request closed without merging**
